apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: af7cuvt15-go
  janus-idp.io/tekton: af7cuvt15-go
  backstage.io/kubernetes-id: af7cuvt15-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: af7cuvt15-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
